production:
  host: https://careerseekers-engine.herokuapp.com
  handle: affectionate-smokescreen-3929
  email: michael.macahilig@careertrackers.org.au
  api_key: d73352d6f9cc64dfa821d90aecf2065067e8254a
